### ISSUE TITLE
Travando BR Player via BR Guide

### ISSUE THREAD

**Issue by pprado** [olavopeixoto/script.brguide#1]
Olavo, boa tarde.
Tenho adorado o BR Play e descobri o BR Guide hoje.
O BR Guide atualizou numa boa, mas quando escolho um programa, por exemplo, Globonews, a transmissão começa bem, mas depois de alguns segundos vai dando umas travadas ou congela.
Tentei várias vezes, dei boot na minha Mi Box por garantia, mas o problema acontecia de novo.
Pensei de ser o inputStream, mas ele está habilitado e se vou via BR Play direto, a transmissão está perfeita.
O BR Guide acessa do BR PLay de alguma forma diferente?

**Comment by pprado** [comment]
Eu esqueci que tinha mudado do Kodi 17 pro 18... Começou a dar problema com o BR Play tb...

Voltei pro Kodi 17 e está funcionando corretamente.

Tem que configurar alguma coisa a mais no Kodi 18?

[]'s

**Comment by pprado** [comment]
Desculpa o spam de mensagem, mas se alguém tiver a mesma dúvida do que eu, já vai ter a resposta também :)

Eu fui na configuração do BR Play e mandei desabilitar o uso do inputStream adaptativo e tudo funcionou como deveria.

[]'s

**Comment by helviojr** [comment]
Mas desabilitando o InputStream, param os canais que usam DRM (Universal, por exemplo)

**Comment by pprado** [comment]
@helviojr veja que o comentário é de 2018. Nessa época não funcionava os canais com DRM, então era preciso manter o InputStream adaptative desabilitado, tanto que ainda há nas configurações do BRPlay uma opção para desabilitar o inputStream.

Atualmente, pode deixar o inputStream HABILITADO que funciona todos os canais.
