### ISSUE TITLE
Lista de canais 

### ISSUE THREAD

**Issue by CaioTheBrain** [olavopeixoto/script.brguide#2]
Olá, Olavo.

Reparei que a lista de canais do BR Guide está defasada em relação ao BR Play

Faltam os canais Futura e Premiere 24h.

É listada uma Rede Globo sem identificação, mas que não funciona. 

São listados todos os canais pagos, independentemente da autorização. Por exemplo o Combate, que eu não tenho acesso. 

Tem como aplicar a verificação da autorização de canais que já tem no BR Play?

**Comment by olavopeixoto** [comment]
Resolvido o problema com a Globo.
Adicionado os canais adicionais.
